"use client";

import React from "react";
import { Download, Terminal } from "lucide-react";

export default function DownloadPage() {
 return (
 <div className="p-4 md:p-8 pt-4">
 <div className="max-w-4xl mx-auto space-y-8">
 <header className="pb-4 border-b border-border">
 <div>
 <h1 className="text-2xl font-bold text-foreground">AutoCAD Integration</h1>
 <p className="text-muted-foreground mt-1 text-sm">Bridge the gap between RDCAD Express and your local AutoCAD environment.</p>
 </div>
 <a 
 href="/rdcad-import.lsp" 
 download="rdcad-import.lsp"
 className="flex items-center gap-2 px-6 py-3 bg-primary hover:bg-indigo-500 text-primary-foreground rounded-lg font-medium transition shadow-lg shadow-indigo-500/20"
 >
 <Download className="w-5 h-5" /> Download Script (.lsp)
 </a>
 </header>

 <div className="bg-card rounded-xl border border-border p-8 space-y-6">
 <h2 className="text-2xl font-semibold text-foreground">How it works</h2>
 <p className="text-muted-foreground text-lg leading-relaxed">
 Downloading DXF files is only half the battle. To truly speed up your workflow, we&apos;ve created a tiny (1KB) AutoLISP companion script. When executed, this script instantly locates the most recent DXF file in your Downloads folder and attaches it to your cursor for immediate insertion into your drawing.
 </p>
 
 <div className="bg-blue-900/20 border border-blue-500/20 p-4 rounded-lg">
 <h4 className="text-primary font-medium mb-1">Compatibility Note</h4>
 <p className="text-sm text-foreground">
 <strong>DXF Files:</strong> The .dxf files generated by RDCAD Express are universally supported and can be opened in <em>any</em> CAD software (AutoCAD, MicroStation, FreeCAD, etc.).<br/>
 <strong>LISP Script:</strong> This script works perfectly in AutoCAD, as well as AutoCAD alternatives that support AutoLISP (like BricsCAD, ZWCAD, and GstarCAD). For other software, simply drag and drop the DXF file into your workspace!
 </p>
 </div>

 <div className="space-y-4 pt-4">
 <h3 className="text-xl font-medium text-foreground">Installation & Usage</h3>
 <ol className="list-decimal list-inside space-y-4 text-muted-foreground">
 <li>
 <span className="text-foreground">Download the script</span> using the button above.
 </li>
 <li>
 <span className="text-foreground">Drag and drop</span> the downloaded <code className="px-1.5 py-0.5 bg-muted rounded text-indigo-500 dark:text-indigo-300">rdcad-import.lsp</code> file directly into your open AutoCAD window to load it for the current session.
 </li>
 <li>
 Type <code className="px-1.5 py-0.5 bg-muted rounded text-emerald-500 dark:text-emerald-300">RDCAD_IMPORT</code> in the AutoCAD command line and press Enter.
 </li>
 <li>
 The newest `.dxf` file from your Downloads folder will instantly appear on your cursor. Click to place!
 </li>
 </ol>
 </div>

 <div className="mt-8 p-4 bg-background rounded-lg border border-border">
 <div className="flex items-center gap-2 mb-2 text-muted-foreground text-sm">
 <Terminal className="w-4 h-4" /> Pro Tip: Persistent Loading
 </div>
 <p className="text-sm text-muted-foreground">
 To avoid dragging and dropping the file every time you open AutoCAD, you can add it to your <strong>Startup Suite</strong>. Type <code className="px-1.5 py-0.5 bg-muted rounded text-foreground">APPLOAD</code> in AutoCAD, click the &quot;Contents...&quot; button under the Startup Suite section, and add the <code className="px-1.5 py-0.5 bg-muted rounded text-indigo-500 dark:text-indigo-300">rdcad-import.lsp</code> file there.
 </p>
 </div>
 </div>
 </div>
 </div>
 );
}
